# Generated by Django 5.0.3 on 2024-04-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('title', models.CharField(max_length=90)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('momo', 'Momo'), ('sekuwa', 'Sekuwa'), ('noodles', 'Noodles'), ('acchar', 'Acchar'), ('set', 'Nepali Set'), ('sel', 'Sel Roti'), ('chatamari', 'Chatamari'), ('offer', 'Offers')], max_length=75)),
            ],
        ),
    ]
