# Generated by Django 5.0.3 on 2024-04-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0002_order_rename_product_fooditems_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='category',
            field=models.CharField(choices=[('momo', 'Momo'), ('sekuwa', 'Sekuwa'), ('noodles', 'Noodles'), ('acchar', 'Acchar'), ('set', 'Nepali Set'), ('sel', 'Sel Roti'), ('chatamari', 'Chatamari'), ('offer', 'Offers')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Food Not Delivered', max_length=100),
        ),
    ]
