# Generated by Django 5.0.3 on 2024-04-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0005_alter_order_status_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='image',
            field=models.ImageField(upload_to='food_images/'),
        ),
    ]
