# Generated by Django 5.0.3 on 2024-05-25 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0007_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='food_item',
        ),
    ]
