# Generated by Django 5.0.3 on 2024-05-25 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed')], default='Pending', max_length=20),
        ),
    ]
