# Generated by Django 5.0.3 on 2024-05-26 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablebook', '0002_tablebooking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablebooking',
            name='status',
        ),
    ]
