# Generated by Django 5.0.3 on 2024-04-09 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useracc', '0002_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
