# Generated by Django 5.0.3 on 2024-04-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useracc', '0005_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
