# Generated by Django 5.0.3 on 2024-05-25 06:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useracc', '0007_blacklistedtoken_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklistedtoken',
            options={'verbose_name': 'Blacklisted Token', 'verbose_name_plural': 'Blacklisted Tokens'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='blacklistedtoken',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
